spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    url: jdbc:mysql://127.0.0.1:3306/hello?userUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456

    # 初始化，最小，最大连接数
    initialSize: 3
    minidle: 3
    maxActive: 100
    # 获取数据库连接等待的超时时间
    maxWait: 60000
    testOnBorrow: false
    testWhileIdle: true
    # 配置多久进行一次检测，检测需要关闭的空闲连接 单位毫秒
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1
    # 配置监控统计拦截的filters,去掉后，监控界面的sql无法统计
    filters: stat,wall,log4j

mybatis:
  # xml文件所在路径
  mapper-locations: classpath:/mappers/*Mapper.xml
  # 几个包的路径
  type-aliases-package: com.example.test.mapper,com.example.test.dto,com.example.test.entity

  configuration:
    # 驼峰命名
    map-underscore-to-camel-case: true
    # 自增主键
    use-generated-keys: true